dist: trusty
before-install:
    - sudo apt-get update -qq
install:
    - sudo apt-get install -qq gcc-avr avr-libc avrdude -y
    - npm install -g wio
script:
    - set -e # Fail on first error
    - for module in $(ls -d */);
      do cd $module;
      wio update pkg . >/dev/null;
      wio pac get >/dev/null;
      wio build;
      cd ..;
      done
